openapi: 3.0.2
info:
  version: 1.0.0
  title: Karuna API
  contact:
    name: Karuna Health API Support
    email: antares@meetkaruna.com
    url: "https://www.meetkaruna.com/"
  x-logo:
    url: "https://developer.meetkaruna.com/logo.png"
  description: >
    # Integrating with Karuna

    ## Overview

    Karuna's platform allows care providers to interact with patients in simple,
    intuitive ways. Patients can have conversations with their care providers
    using tools and channels they already have access to (phone calls, SMS,
    email, etc.), and care providers can see all of these conversations in a
    single shared inbox for each patient.


    Karuna's APIs expose a broad set of platform functionality, and can be used
    to build out deep integrations.

    ## Core Concepts

    ### Patients

    Patients in Karuna represent the end users of the system. To patients,
    Karuna's platform is invisible. A patient can use Karuna's platform to
    communicate with members of their care team using different Channels they
    already have access to (e.g., phone calls, SMS, email, etc.).

    ### Navigators

    Navigators are the care providers who provide services to their patients. A
    navigator can participate in conversations with their patients using
    Karuna's platform, and have all of their interactions via different channels
    represented in a single shared inbox per patient.

    ### Care Teams

    Navigators and Patients are connected to each other in Karuna via Care
    Teams. A Care Team Member represents a single relationship between a
    Navigator and a Patient. This allows Navigators to have multiple Patients,
    and for a Patient to have multiple Navigators.

    ### Channels

    A Channel in Karuna represents a contact method for a given Patient.
    Patients can have multiple Channels of different types (sources),
    representing different ways messages can flow to and from a Patient. For
    example, a given Patient's channels might include a landline, a cell phone
    number, and two email addresses.

    ### Interactions

    An Interaction in Karuna represents a high-level unit of communication
    between a Navigator and Patient, as seen by the Navigator. If a Navigator
    wants to send an SMS to a Patient, they will create an Interaction
    representing the intent to deliver this message to the Patient via
    particular patient Channel. Karuna's platform will then translate the
    Interaction into an actual Message which will get delivered to the Patient
    via the correct Channel. Similarly, an incoming Message from a Patient will
    have an associated Interaction created post-hoc.


    Interactions represent all possible conceptual interactions between Patients
    and Navigators on Karuna's platform, including phone calls, missed calls,
    SMS messages, emails, etc.

    ### Messages

    A message represents an actual instance of a delivered or received message
    on Karuna's platform. Messages can be created via Interactions (if
    originated on Karuna's platform and delivered outbound to the Patient), or
    they can be created via an incoming response from a Patient.

servers:
  - url: "https:asdf"
    description: Development server

  - url: "https:asdf2"
    description: Production server

tags:
  - name: User Tokens
    description:
      These endpoints allow you to obtain a `user_token` and check its validity.

  - name: Organizations
    description: Endpoints to manage Organizations.

  - name: Patients
    description: Endpoints to manage Patients.

  - name: Circle of Care Members
    description: Endpoints to manage Circle of Care Members.

  - name: Navigators
    description: Endpoints to manage Navigators.

  - name: Channels
    description: Endpoints to manage Channels.

  - name: Interactions
    description: Endpoints to manage Interactions.

    # TODO(gualcm): maybe add Labels and Templates tag

paths:
  /labels:
    $ref: "paths/labels.yaml"

  /templates:
    $ref: "paths/templates/index.yaml"

  /tokens/check:
    $ref: "paths/tokens/check.yaml"

  /organizations/{slug}:
    $ref: "paths/organizations/{slug}.yaml"

  /patients:
    $ref: "paths/patients/index.yaml"
  /patients/archive:
    $ref: "paths/patients/archive.yaml"
  /patients/merge:
    $ref: "paths/patients/merge.yaml"
  /patients/{patientId}:
    $ref: "paths/patients/{patientId}/index.yaml"
  /patients/{patientId}/labels/{labelId}:
    $ref: "paths/patients/{patientId}/labels/{labelId}.yaml"
  /patients/{patientId}/call_forwarding_override:
    $ref: "paths/patients/{patientId}/call_forwarding_override.yaml"
  /patients/{patientId}/follow:
    $ref: "paths/patients/{patientId}/follow.yaml"
  /patients/{patientId}/unfollow:
    $ref: "paths/patients/{patientId}/unfollow.yaml"
  /patients/{patientId}/primary_navigator:
    $ref: "paths/patients/{patientId}/primary_navigator.yaml"
  /patients/{patientId}/channels:
    $ref: "paths/patients/{patientId}/channels/index.yaml"
  /patients/{patientId}/channels/{channelId}:
    $ref: "paths/patients/{patientId}/channels/{channelId}.yaml"
  /patients/{patientId}/interactions:
    $ref: "paths/patients/{patientId}/interactions/index.yaml"
  /patients/{patientId}/care_team_members/{careTeamMemberId}:
    $ref: "paths/patients/{patientId}/care_team_members/{careTeamMemberId}.yaml"
  /patients/{patientId}/circle_of_care_members:
    $ref: "paths/patients/{patientId}/circle_of_care_members/index.yaml"
  /patients/{patientId}/circle_of_care_members/{circleOfCareMemberId}:
    $ref: "paths/patients/{patientId}/circle_of_care_members/{circleOfCareMemberId}/index.yaml"
  /patients/{patientId}/circle_of_care_members/{circleOfCareMemberId}/channels:
    $ref: "paths/patients/{patientId}/circle_of_care_members/{circleOfCareMemberId}/channels/index.yaml"
  ? /patients/{patientId}/circle_of_care_members/{circleOfCareMemberId}/channels/{channelId}
  : $ref: "paths/patients/{patientId}/circle_of_care_members/{circleOfCareMemberId}/channels/{channelId}.yaml"
  ? /patients/{patientId}/circle_of_care_members/{circleOfCareMemberId}/interactions
  : $ref: "paths/patients/{patientId}/circle_of_care_members/{circleOfCareMemberId}/interactions.yaml"

  /navigators/token:
    $ref: "paths/navigators/token.yaml"
  /navigators/delete:
    $ref: "paths/navigators/delete.yaml"
  /navigators/reset_password:
    $ref: "paths/navigators/reset_password.yaml"
  /navigators/update_password:
    $ref: "paths/navigators/update_password.yaml"
  /navigators:
    $ref: "paths/navigators/index.yaml"
  /navigators/{navigatorId}:
    $ref: "paths/navigators/{navigatorId}/index.yaml"
  /navigators/{navigatorId}/channels:
    $ref: "paths/navigators/{navigatorId}/channels/index.yaml"
  /navigators/{navigatorId}/channels/{channelId}:
    $ref: "paths/navigators/{navigatorId}/channels/{channelId}.yaml"

components:
  securitySchemes:
    user_token:
      $ref: "components/securitySchemes/user_token.yaml"
    service_token:
      $ref: "components/securitySchemes/service_token.yaml"
